FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/app.py", "--server.address", "0.0.0.0"]